In [10]:
import numpy as np

matrix = np.array([
    [ 0,  0,  0,  0,  0],
    [ 0,  0, -1, -1,  0],
    [ 0,  0, -1, -1,  0],
    [ 0,  0,  0,  0,  0],
    [ 0,  0,  0,  0,  0]
])

transposed = matrix.T  # now columns become rows

# Compare each row to the next
row_diffs = transposed[:-1] == transposed[1:]
identical = np.all(row_diffs, axis=1)
slices = np.where(~identical)[0] 
boundaries = [0] + list(slices + 1) + [len(transposed)]
cells = []
for i in range(len(boundaries) - 1):
    col_start = boundaries[i]
    col_end   = boundaries[i+1] - 1
    
    # free rows = any row in this column that isn't -1
    sample_col = transposed[col_start]
    free_rows = list(np.where(sample_col != -1)[0])
    
    cells.append({
        'col_start': col_start,
        'col_end':   col_end,
        'free_rows': free_rows
    })

def sweep_cell(matrix, cell):
    col_start = cell['col_start']
    col_end   = cell['col_end']
    free_rows = cell['free_rows']
    
    for i in range(len(free_rows)):   # i = 0,1,2...
        row = free_rows[i]            # actual row index from the list
        
        if i % 2 == 0:                # even → left to right
            for col in range(col_start, col_end + 1):
                if matrix[row][col] != -1:
                    matrix[row][col] = 1
            print(matrix[row][col_start:col_end + 1])
        
        else:                         # odd → right to left
            for col in range(col_end, col_start - 1, -1):
                if matrix[row][col] != -1:
                    matrix[row][col] = 1
            print(matrix[row][col_start:col_end + 1][::-1])

for cell in cells:
    print(f"\n--- Cell cols {cell['col_start']}-{cell['col_end']} ---")
    sweep_cell(matrix, cell)

print("\n--- Final Matrix ---")
print(matrix)


--- Cell cols 0-1 ---
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]

--- Cell cols 2-3 ---
[1 1]
[1 1]
[1 1]

--- Cell cols 4-4 ---
[1]
[1]
[1]
[1]
[1]

--- Final Matrix ---
[[ 1  1  1  1  1]
 [ 1  1 -1 -1  1]
 [ 1  1 -1 -1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]
